// Generated by map/generate-map.mjs. Positions in % of the map image.
export const MAP_ASPECT = 624 / 384;
export const MAP_PINS: { name: string; primary: boolean; left: number; top: number }[] = [
  {
    "name": "Pontassieve",
    "primary": true,
    "left": 44.4,
    "top": 81.1
  },
  {
    "name": "Helsinki",
    "primary": false,
    "left": 56.71,
    "top": 41.09
  }
];
export const MAP_LABELS: {
  text: string;
  kind: "city" | "country";
  left: number;
  top: number;
}[] = [
  {
    "text": "Helsinki",
    "kind": "city",
    "left": 56.71,
    "top": 41.09
  },
  {
    "text": "Florence",
    "kind": "city",
    "left": 44.24,
    "top": 81.12
  },
  {
    "text": "ITALY",
    "kind": "country",
    "left": 46.56,
    "top": 85.5
  },
  {
    "text": "FINLAND",
    "kind": "country",
    "left": 58.95,
    "top": 24.1
  }
];
