// Builds the static Contact map: public/office-map.png and
// components/officeMapLabels.ts (pin and label positions, set in HTML so the
// labels use the page's LM Roman font).
//
// The image freezes the old interactive Leaflet map's default view: CARTO
// light_nolabels tiles at zoom 3, greyscale, framing Italy and Finland in a
// 624 x 384 px box (the text column at its widest). Tiles are fetched at @2x,
// so the image is 1248 x 768 and stays sharp on retina screens.
//
// Run from this folder, with the CARTO key and (on this machine) the proxy:
//   npm i --no-save sharp
//   HTTPS_PROXY=http://127.0.0.1:8888 NEXT_PUBLIC_CARTO_KEY=... node generate-map.mjs
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import sharp from "sharp";

const KEY = process.env.NEXT_PUBLIC_CARTO_KEY;
if (!KEY) throw new Error("NEXT_PUBLIC_CARTO_KEY is not set");

const ZOOM = 3;
const W = 624; // CSS px
const H = 384;
const SCALE = 2;
const TILE = 256;
// Same bounds the Leaflet map fitted.
const BOUNDS = { south: 36.0, west: 2.0, north: 70.5, east: 33.0 };

const OFFICES = [
  { name: "Pontassieve", lat: 43.7785, lng: 11.4321, primary: true },
  { name: "Helsinki", lat: 60.1699, lng: 24.9384, primary: false },
];
const COUNTRY_LABELS = [
  { text: "ITALY", lat: 41.6, lng: 13.8 },
  { text: "FINLAND", lat: 65.4, lng: 27.4 },
];
const CITY_LABELS = [
  { text: "Helsinki", lat: 60.1699, lng: 24.9384 },
  { text: "Florence", lat: 43.7696, lng: 11.2558 },
];

// Web Mercator, in zoom-level pixels.
const world = TILE * 2 ** ZOOM;
const px = (lat, lng) => {
  const s = Math.sin((lat * Math.PI) / 180);
  return [
    ((lng + 180) / 360) * world,
    (0.5 - Math.log((1 + s) / (1 - s)) / (4 * Math.PI)) * world,
  ];
};
const [bx0, by1] = px(BOUNDS.south, BOUNDS.west);
const [bx1, by0] = px(BOUNDS.north, BOUNDS.east);
const x0 = Math.round((bx0 + bx1) / 2 - W / 2);
const y0 = Math.round((by0 + by1) / 2 - H / 2);

const tiles = [];
for (let ty = Math.floor(y0 / TILE); ty <= Math.floor((y0 + H) / TILE); ty++) {
  for (let tx = Math.floor(x0 / TILE); tx <= Math.floor((x0 + W) / TILE); tx++) {
    const url = `https://a.basemaps.cartocdn.com/light_nolabels/${ZOOM}/${tx}/${ty}@2x.png?key=${KEY}`;
    const input = execFileSync("curl", ["-sfL", url]);
    tiles.push({
      input,
      left: (tx * TILE - x0) * SCALE,
      top: (ty * TILE - y0) * SCALE,
    });
  }
}

// Composite onto a canvas big enough for every whole tile, then crop.
const pad = TILE * SCALE;
const stitched = await sharp({
  create: {
    width: W * SCALE + 2 * pad,
    height: H * SCALE + 2 * pad,
    channels: 3,
    background: "#f2f2f2",
  },
})
  .composite(tiles.map((t) => ({ ...t, left: t.left + pad, top: t.top + pad })))
  .png()
  .toBuffer();
await sharp(stitched)
  .extract({ left: pad, top: pad, width: W * SCALE, height: H * SCALE })
  .grayscale()
  .png({ compressionLevel: 9, palette: true })
  .toFile(new URL("../public/office-map.png", import.meta.url).pathname);

const pct = (lat, lng) => {
  const [x, y] = px(lat, lng);
  return {
    left: +(((x - x0) / W) * 100).toFixed(2),
    top: +(((y - y0) / H) * 100).toFixed(2),
  };
};
writeFileSync(
  new URL("../components/officeMapLabels.ts", import.meta.url),
  `// Generated by map/generate-map.mjs. Positions in % of the map image.
export const MAP_ASPECT = ${W} / ${H};
export const MAP_PINS: { name: string; primary: boolean; left: number; top: number }[] = ${JSON.stringify(
    OFFICES.map((o) => ({ name: o.name, primary: o.primary, ...pct(o.lat, o.lng) })),
    null,
    2
  )};
export const MAP_LABELS: {
  text: string;
  kind: "city" | "country";
  left: number;
  top: number;
}[] = ${JSON.stringify(
    [
      ...CITY_LABELS.map((c) => ({ text: c.text, kind: "city", ...pct(c.lat, c.lng) })),
      ...COUNTRY_LABELS.map((c) => ({ text: c.text, kind: "country", ...pct(c.lat, c.lng) })),
    ],
    null,
    2
  )};
`
);
console.log(`wrote public/office-map.png (${tiles.length} tiles) and components/officeMapLabels.ts`);
